//
//  File.swift
//  
//
//  Created by Alex - SEEMOO on 19.06.20.
//

import XCTest
@testable import ASN1Decoder

class ASN1SignatureTests: XCTestCase {
    
    func testGetSignatureFromPKCS7() throws {
        let signatures = try PKCS7(data: self.asn1TestFile).signatures
        XCTAssertEqual(signatures?.count, 1)
    }
    
    private var asn1TestFile: Data {
        let b64String =
        """
        MIAGCSqGSIb3DQEHAqCAMIACAQExCzAJBgUrDgMCGgUAMIAGCSqGSIb3DQEHAaCA
        JIAEggPoPD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPCFE
        T0NUWVBFIHBsaXN0IFBVQkxJQyAiLS8vQXBwbGUvL0RURCBQTElTVCAxLjAvL0VO
        IiAiaHR0cDovL3d3dy5hcHBsZS5jb20vRFREcy9Qcm9wZXJ0eUxpc3QtMS4wLmR0
        ZCI+CjxwbGlzdCB2ZXJzaW9uPSIxLjAiPgo8ZGljdD4KCTxrZXk+VmVyc2lvbjwv
        a2V5PgoJPGludGVnZXI+MjwvaW50ZWdlcj4KCTxrZXk+YWx0RHNJRDwva2V5PgoJ
        PHN0cmluZz4wMDE5NDEtMDUtMjAyYWRmYmItMjQ5My00MjQ3LWEyMGEtODQzZjFm
        MmVmZWE4PC9zdHJpbmc+Cgk8a2V5PmVuY0RzSUQ8L2tleT4KCTxzdHJpbmc+MDAx
        OTQxLTA1LTIwMmFkZmJiLTI0OTMtNDI0Ny1hMjBhLTg0M2YxZjJlZmVhODwvc3Ry
        aW5nPgoJPGtleT5TdWdnZXN0VmFsaWREdXJhdGlvbjwva2V5PgoJPGludGVnZXI+
        MjU5MjAwMDwvaW50ZWdlcj4KCTxrZXk+VmFsaWRBc09mPC9rZXk+Cgk8ZGF0ZT4y
        MDIwLTA2LTE1VDA3OjQ2OjEwWjwvZGF0ZT4KCTxrZXk+VmFsaWRhdGVkRW1haWxI
        YXNoZXM8L2tleT4KCTxhcnJheT4KCQk8c3RyaW5nPmMwNjFhOTQxM2JhZTgyNjlm
        N2RiNTczYWY5ZDVjMGU0NDlmYjI5ZWIwZDllZGRkNzAxZTg0NWU1MjY3OWFjNWU8
        L3N0cmluZz4KCQk8c3RyaW5nPjZlOTdkMmFjNWUwMGZiN2ZhZjM2ODJkYTg4ZWI1
        N2E1OTU0MDVhNTk3MjZkZWNlMjljYjQwMDMwOTc2OWVhYzc8L3N0cmluZz4KCQk8
        c3RyaW5nPjUyM2VjOTBhN2U0MTZjZDJhYzhlMmFiNzA0NzNlZTIyOGFjNzExNWUy
        ODhjMDMwOWFjMzE5YTQyODVkOWYzNmQ8L3N0cmluZz4KCQk8c3RyaW5nPjUyM2E3
        MjRjZWYzYmYyMTQ5YTliYjFlMjMzNThmYjY1MDZiODM4MGQ0OGYyNzgzMGU1M2Mx
        YjIyYmFhMWU4NDA8L3N0cmluZz4KCQk8c3RyaW5nPjRjMjQ5MTExMDFkYjUzYTQ3
        MDk2NGNjM2FiMDg4ZDhhNTdiMjIyZmIzMWZhOTFhYzRkYjM4MjU3MDVkY2U1YWY8
        L3N0cmluZz4KCQk8c3RyaW5nPjhhNTEyNDUzMTc5NmE5Y2ZiYmE5OGU5ZWJhNwSB
        0TdmOTAxNmQ3NmU3ZWQ2ODU0NGFkMmIyNDNmZTFmZDQ0MjI1ZTI8L3N0cmluZz4K
        CTwvYXJyYXk+Cgk8a2V5PlZhbGlkYXRlZFBob25lSGFzaGVzPC9rZXk+Cgk8YXJy
        YXk+CgkJPHN0cmluZz44NjNiODU2NjZlODNhN2RlNjQyMzNlMDQ2MDJlOTU0NWZh
        YjY5NTY1MjM2ZDU4MDJkODBiMmQyMjMwMWRkMWExPC9zdHJpbmc+Cgk8L2FycmF5
        Pgo8L2RpY3Q+CjwvcGxpc3Q+AAAAAAAAoIAwggUMMIID9KADAgECAghqlRtGysFw
        1zANBgkqhkiG9w0BAQsFADCBjDFAMD4GA1UEAww3QXBwbGUgQXBwbGljYXRpb24g
        SW50ZWdyYXRpb24gMiBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTEmMCQGA1UECwwd
        QXBwbGUgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkxEzARBgNVBAoMCkFwcGxlIElu
        Yy4xCzAJBgNVBAYTAlVTMB4XDTE4MDkxOTIxMjYxMVoXDTIwMDkxODE4NTAwMFow
        KDEmMCQGA1UEAwwdQXBwbGUgSUQgVmFsaWRhdGlvbiBSZWNvcmQgMDUwggEiMA0G
        CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDGglDbNM7Vvv++GgTvvPYW1pgMP1i/
        1WlbZYIf1BJhBVXSDoBV1U04w1Y2JEx+FnwlGarUhxKNzMvtMWXKhp5uSwg116Ji
        /KucC20EcU5GWW2PNMuFW+blTsYkRfGPS0WksVs8lrVUjnLxUidzPmTjfYmXZiyo
        csCRBPev0XHABMmXmb23zV+1xudaO18kJXXcNlsdU/41pjv6LuMFBoit9cG/SW8O
        xxemm0SObTRIwX3rX8RtU1yQFhf56wSBTt2dSInHgZNeqi3RrSMEYJq+oeskMWAf
        1ksF3ZdwV9yU6qcYuyecuDHWC3eIzfjhH3Pqaag8RFElMFzcyPLPnu1dAgMBAAGj
        ggHTMIIBzzAJBgNVHRMEAjAAMB8GA1UdIwQYMBaAFPe+fCFgkds9G3vYOjKBad+e
        bH+bMEEGCCsGAQUFBwEBBDUwMzAxBggrBgEFBQcwAYYlaHR0cDovL29jc3AuYXBw
        bGUuY29tL29jc3AwMy1hYWkyY2EwMjCCARwGA1UdIASCARMwggEPMIIBCwYJKoZI
        hvdjZAUBMIH9MIHDBggrBgEFBQcCAjCBtgyBs1JlbGlhbmNlIG9uIHRoaXMgY2Vy
        dGlmaWNhdGUgYnkgYW55IHBhcnR5IGFzc3VtZXMgYWNjZXB0YW5jZSBvZiB0aGUg
        dGhlbiBhcHBsaWNhYmxlIHN0YW5kYXJkIHRlcm1zIGFuZCBjb25kaXRpb25zIG9m
        IHVzZSwgY2VydGlmaWNhdGUgcG9saWN5IGFuZCBjZXJ0aWZpY2F0aW9uIHByYWN0
        aWNlIHN0YXRlbWVudHMuMDUGCCsGAQUFBwIBFilodHRwOi8vd3d3LmFwcGxlLmNv
        bS9jZXJ0aWZpY2F0ZWF1dGhvcml0eTAdBgNVHQ4EFgQU7c7Nk5Bg68kAh4M9JIqC
        OtBbDe8wDgYDVR0PAQH/BAQDAgeAMA8GCSqGSIb3Y2QGGQQCBQAwDQYJKoZIhvcN
        AQELBQADggEBACDrFmCWqy9bBdfW5WanBHUStpnpOkJyrvLLyAC+JnWPgQH1q4b5
        OA5/anNOHMyJXDS+OjX6nUM1oRWXCPbW6fbo8QGwgXLsCAN9URRnepPlocaRPfYh
        LXasWj5nPZmRtSlpk+ofm3dclj2+52m69bK5cFsgucyZH0b/upoNli9TENcqh33n
        llngn7ovgag6dr2j3Xs8I01MmG7JcAt9yNsF0j64a+XdwAe88k9B39+5oKyczntj
        Lc6VPZHVVH6QqeoAQwp8i+D0nfGmEyeYwMHkuI8bvqe5NIJ+GuhOX3+x5PSMczzb
        l7j8FSQUYW9JI9RWT1Kf4YThoRIAx1qYLZ0wggQYMIIDAKADAgECAggEuftlkUqY
        aTANBgkqhkiG9w0BAQsFADBiMQswCQYDVQQGEwJVUzETMBEGA1UEChMKQXBwbGUg
        SW5jLjEmMCQGA1UECxMdQXBwbGUgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkxFjAU
        BgNVBAMTDUFwcGxlIFJvb3QgQ0EwHhcNMTMwNTI0MTc0MzM3WhcNMjgwNTI0MTc0
        MzM3WjCBjDFAMD4GA1UEAww3QXBwbGUgQXBwbGljYXRpb24gSW50ZWdyYXRpb24g
        MiBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTEmMCQGA1UECwwdQXBwbGUgQ2VydGlm
        aWNhdGlvbiBBdXRob3JpdHkxEzARBgNVBAoMCkFwcGxlIEluYy4xCzAJBgNVBAYT
        AlVTMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuEihZ2xWCJ3lcMVG
        9K+F47063qHn2ag2PBlipXwVoEeza4EbEKz+2HTmDjWwWE902KP+7S3upHMlWdSW
        3CbPnSeLVJzckrHgMxIYYpnIua82GKRqgZGnFW3d3Q8tzAWBHX0QzCmJo8kMmaqi
        7NkBZ2kHAjwXv0QoJLHELDXWsQIACCXvUKcH2yXGw09vW4e+KvGTp9RsXrI5LgSp
        4W0cO645cT8E87n0V50jAE+Zg16f8AwBWL610ezXsn7CZeLx7Dym/G7bVrPuCgay
        C0vJovDxMfau3jVsw4BeUGOQtrptXMDjnyaDSh3em6mwWm/7m2uB7N3fMt78LkKi
        ynha1wIDAQABo4GmMIGjMB0GA1UdDgQWBBT3vnwhYJHbPRt72DoygWnfnmx/mzAP
        BgNVHRMBAf8EBTADAQH/MB8GA1UdIwQYMBaAFCvQaUeUdgn+9GuNLkCm90dNfwhe
        MC4GA1UdHwQnMCUwI6AhoB+GHWh0dHA6Ly9jcmwuYXBwbGUuY29tL3Jvb3QuY3Js
        MA4GA1UdDwEB/wQEAwIBBjAQBgoqhkiG92NkBgIDBAIFADANBgkqhkiG9w0BAQsF
        AAOCAQEAlc2N/aRd9fHAh0mH3bMzk62EEtAhk+PZ1tqvCSKCYA08WULxLQGTtj//
        9Cr07hVqeMEu+ztMEK5lQ8vPqA7rPTeQRS8ISo2oiGsZFxHimtvvZ7gH8eTYhgtx
        d9PzieCvpOooBaQ/NHllNoNUEkFx1x0SIdxQVUXOjrz33FXQs8ooUaxzUQeseX+L
        bpKgNwlhMS+h0brr4Vw3wNjRGwzn4BBSQqSUf4v2YCJgfKDAP8GVhdXCJ2OwYlaZ
        7SX0zIiZmdxUHBcFAbd56IGFOEDCuQjtTWLUK/YpBvFnoeEdBY1yDHcO9qCUK1GI
        EoRT8vOSCQiE8+i/oRMmz/wXkje7QAAAMYICTDCCAkgCAQEwgZkwgYwxQDA+BgNV
        BAMMN0FwcGxlIEFwcGxpY2F0aW9uIEludGVncmF0aW9uIDIgQ2VydGlmaWNhdGlv
        biBBdXRob3JpdHkxJjAkBgNVBAsMHUFwcGxlIENlcnRpZmljYXRpb24gQXV0aG9y
        aXR5MRMwEQYDVQQKDApBcHBsZSBJbmMuMQswCQYDVQQGEwJVUwIIapUbRsrBcNcw
        CQYFKw4DAhoFAKCBiDAYBgkqhkiG9w0BCQMxCwYJKoZIhvcNAQcBMBwGCSqGSIb3
        DQEJBTEPFw0yMDA2MTUwNzQ2MTBaMCMGCSqGSIb3DQEJBDEWBBQJG/XSacB7i+8X
        pUuOUvlyEb1rzzApBgkqhkiG9w0BCTQxHDAaMAkGBSsOAwIaBQChDQYJKoZIhvcN
        AQEBBQAwDQYJKoZIhvcNAQEBBQAEggEAYBLQIZFKYXa1jfYROYED9CEriSuX8lDT
        hZdTMkdHdQ2o4PCxFANTugT6SHOcRTe4zBJ5hM7hiW1RbX+ORCZxeZW7Tn11Ppfm
        8woxsHorJ6iWlohOIxuYS9KMHJXSW+HLSUovXCj+dQEiRtDwAt0A0FCmsEK6hJxg
        bZSdNLaN2keMAf12zib/2onr1IwTkMW8oc6cY2DBElCDX1MW58h8/bISJeIVb0XV
        TrZ6ZKk1vqyiMJ/oOf7FC6F8rlX+l5CbBhF4CKCQqGtpJSWNjSFhmHjCKS50RB83
        Guvg233i9G/xYEu5tkcF8tSKIvS/BZ/2g0nEOvHA8Owo+qu7I0G3oQAAAAAAAA==
        """
        
        return Data(base64Encoded: b, options: <#T##Data.Base64DecodingOptions#>)
    }
}
